---
title: "CaseStudyProject"
author: "C. Banks"
date: "June 22, 2016"
output: html_document
---

*For my project, I will present statistics on GDP rankings.  The data will come from the World Banks data catalog providing GDP data for 190 ranked countries and for educational data.*

#The Plan consists of steps and related R code

Identify source file, makefile, markdown files and readme file:

###Load the Gross Domestic Product data for the 190 ranked countries in this data set: 
###https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv 

###Unzip and Load the educational data from this data set: 
###https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv

##Note:  If there are problems with this file download then go to World Bank and try this file:
###http://databank.worldbank.org/data/download/Edstats_csv.zip
###temp <- tempfile()
###download.file("http://databank.worldbank.org/data/download/Edstats_csv.zip",temp)
###Educraw <- read.csv(unz(temp, "EdStats_Country.csv"))
###unlink(temp)

Prepare the codebook as follows:

###Set up working directory to ensure all files are contained in case study project directory
###getwd(current working directory)
###setwd(desired working directory)
###setwd("C:/Users/Celia/Documents/SMU/MSDS6360/Week6/CaseStudy/CaseStudyProject")

###required install.packages
###downloader
###RCurl
###ggplot2
###repmis
###plyr
###reshape2
###Identify R libraries to load
###Loader
###RCurl
###ggplot2
###repmis
###plyr
###reshape2

Analyze Data - Part 1

###Analysis consists of identifying files for download, tidying raw files, 
###Download GDP file directly to working directory from Internet 
###download("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", destfile="gdp.csv")
###download("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv", destfile="education.csv")
###Note: DO THIS IF YOU HAVE PROBLEMS WITH EDUCATIOND DATA SET DOWNLOAD
###Download and unzip Education file to working directory from Internet, load into R
###as raw file
###temp <- tempfile()
###download.file("http://databank.worldbank.org/data/download/Edstats_csv.zip",temp)
###educationraw <- read.csv(unz(temp, "EdStats_Country.csv"))
###unlink(temp)


### confirm files downloaded
###list.files()
###Create data frames from downloaded csv files
###gdpraw <- read.csv("gdp.csv")
###educationraw <-read.csv("education.csv")
###Take a snapshot of file contents and
###see what shape data is in
###head(gdpraw, 15)
###tail(gdpraw)

###str(gdpraw)
###there are NA values in cols x.1, x.5 through x.8 throughout,
###may want to remove the columns. Instructions for case study
###are to remove any NAs, but do a count of them as missing values
###rename field to something meaningful
###change field types from factor to char and numeric
###where needed

###head(educationraw, 15)
###tail(educationraw)

###Look at variable names and types and some preliminary data
###str(educationraw)


###Try to minimize if not eliminate the factor var types
###Re-read files so that character vectors are not changed
###to factors and leave in headers
###gdpraw2 <- read.csv("gdp.csv", stringsAsFactors=FALSE, header=FALSE)
###educationraw2 <- read.csv("education.csv", stringsAsFactors=FALSE, header=FALSE)

###[Use this if education data is suspect]
###temp <- tempfile()
###download.file("http://databank.worldbank.org/data/download/Edstats_csv.zip",temp)
###educationraw2 <- read.csv(unz(temp, "EdStats_Country.csv"), #stringsAsFactors=FALSE, header=FALSE)
###unlink(temp)


Data analysis part 2 -- tidy process: Goal of analysis:  GDP rankings, by country, income levels, education levels

###For educationraw2:
###$V1 (countrycode), $V3 (income group) - just pull out these two columns from educationraw2

###create edufinal extracting only rows for $V1-$V3
###edufinal <- subset(educationraw2, select = V1:V3)

###For gdpraw2:
###$V1 (countrycode), $V2([gdp]ranking)
###line 6 is where data begins and line 236 [6:236] is where it ends;
###create gdpfinal from gdpraw without headers and pull in rows 6 to 236
###gdpfinal <- gdpraw2[6:236,]

###column $V2 just counts the rows and is not needed
###column $V3 contains all NAs, remove it
###cols $V7 through $V10 contain all NAs, remove them

###count how many NAs are in dataset
###sum(is.na(gdpfinal))

###extract columns containing data - $V1, $V4, $V5
###gdpfinal2  <- gdpfinal[c(1,4:5)]

###confirm scaled down dataset
###str(gdpfinal2)

###For edufinal and gdpfinal2:
###rename columns to something meaningful
###now create column names in edufinal and gdpfinal2
###names(edufinal) <-c("CountryShortName", "CountryLongName", "IncomeGroup")
###names(gdpfinal2) <-c("CountryShortName", "CountryLongName", "GDP")

###confirm the var name changes:
###str(edufinal)
###str(gdpfinal2)

###Merge the datasets on CountryShortName
###clean01 <- merge(gdpfinal2, edufinal, by="CountryShortName", all=TRUE)

###confirm merge
###str(clean01)

###For merged dataset clean01:
###In GDP column set NAs to 0.001 and convert it to numeric
###check data in GDP to ensure no NAs
###clean01$GDP[is.na(clean01$GDP)] <- 0.001

###now remove commas to convert to numeric
###clean01$GDP <- as.numeric(gsub('[,]', '', clean01$GDP))

###confirm commas have been removed and var type is numeric
###head(clean01)
###tail(clean01)
###str(clean01)

###Count NAs in dataset before rows with NAs
###count how many IDs match
###sum(!is.na(unique(clean01$GDP)))
###there are 204 IDs that match

###count how many NAs are in dataset
###sum(is.na(clean01))
###there are 52 rows that contain NAs

###any NA values are not relevant to analysis, so
###remove those rows from dataset
###clean02 <- na.omit(clean01)

###look at data to confirm tidy
###str(clean02)
###head(clean02, 20)
###tail(clean02, 10)

Data Analysis -- Part 3 Presentation and Interpretation

###sort data on country short name
###clean02[order(clean02$CountryShortName),]
###set IncomeGroup as factor type
###then declare the levels

###clean02$IncomeGroup <- as.factor(clean02$IncomeGroup)
###levels(clean02$IncomeGroup)

###average GDP rankings for "High income: OECD"
###and "High income: nonOECD" groups
###ddply(clean02, ~IncomeGroup, summarize, avgGDP = mean(GDP))

###Plot by Income Group
###qplot(IncomeGroup, data=clean02, geom="density", color=factor(IncomeGroup), xlab="IncomeGroup", ylab="GDP-Ranking")
###and "High income: nonOECD" groups
###aggregate(x = clean02$GDP, by = list(clean02$IncomeGroup), FUN = "quantile")
###A two-way contingency table Ranking vs. Income Group
###with(clean02, table(cut(GDP, quantile(GDP)), IncomeGroup))


#Answers to Case Study Questions
###Questions
*Match the data based on the country shortcode. How many of the IDs match?*
###Answer: 204

Sort the data frame in ascending order by GDP rank (so United States is last). 
What is #the 13th country in the resulting data frame?
###Answer:  (AZE - Azerbeijan)

What are the average GDP rankings for the "High income: OECD" and "High income:nonOECD" groups?
###Answer:  High income: OECD  1483917.13; High income: nonOECD   104349.83

Plot the GDP for all of the countries. Use ggplot2 to color your plot by Income Group.
###Answer:  See the qplot output from code

Cut the GDP ranking into 5 separate quantile groups. Make a table versus 
Income.Group. How many countries are Lower middle income but among the 
38 nations with highest GDP?
###Answer:  See the contingency table output from code.  I had problems transforming the e numbers.


#References
###Additional info on extracting cols/data from a dataset retrieved on June 20, 2016 from 
###http://www.statmethods.net/management/subset.html
###SMU 2016-0509 MSDS 6306 Week 6 Lectures on Case Study Project
###R Help documentation
```{r}
##Set up working directory to ensure all files are contained 
##in case study project directory
##getwd(current working directory)
##getwd()
##setwd(desired working directory)
##setwd("C:/Users/Celia/Documents/SMU/MSDS6360/Week6/CaseStudy/CaseStudyProject")

##required install.packages
##downloader
##RCurl
##ggplot2
##repmis
##plyr
##reshape2
##Identify R libraries to load
##loader
library(downloader)

##RCurl
library(RCurl)

##ggplot2
##install.packages("ggplot2")
library(ggplot2)

##repmis
library(repmis)

##plyr
library(plyr)

##reshape2
library(reshape2)

##analysis consists of identifying files for download, tidying raw files, 
##Download GDP file directly to working directory from Internet 
download("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", destfile="gdp.csv")
download("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv", destfile="education.csv") 

##Note: DO THIS IF YOU HAVE PROBLEMS WITH EDUCATIOND DATA SET DOWNLOAD
##Download and unzip Education file to working directory from Internet, load into R 
##as raw file 
##temp <- tempfile()
##download.file("http://databank.worldbank.org/data/download/Edstats_csv.zip",temp)
##educationraw <- read.csv(unz(temp, "EdStats_Country.csv"))
##unlink(temp)

##confirm files downloaded
list.files()

##Create data frames from downloaded csv files
gdpraw <- read.csv("gdp.csv")
educationraw <-read.csv("education.csv")

##Take a snapshot of file contents and 
##see what shape data is in
head(gdpraw, 15)
tail(gdpraw)
str(gdpraw)
##there are NA values in cols x.1, x.5 through x.8 throughout,
##may want to remove the columnsâ?¦.instructions for case study
##are to remove any NAs, but do a count of them as missing values
##rename field to something meaningful
##change field types from factor to char and numeric 
##where needed
head(educationraw, 15)
tail(educationraw)
##Look at variable names and types and some preliminary data
str(educationraw)
##Try to minimize if not eliminate the factor var types
##Re-read files so that character vectors are not changed
##to factors and leave in headers
gdpraw2 <- read.csv("gdp.csv", stringsAsFactors=FALSE, header=FALSE)
educationraw2 <- read.csv("education.csv", stringsAsFactors=FALSE, header=FALSE)

              #[Use this if education data is suspect]
##temp <- tempfile()
##download.file("http://databank.worldbank.org/data/download/Edstats_csv.zip",temp)
##educra2 <- read.csv(unz(temp, "EdStats_Country.csv"), 
##stringsAsFactors=FALSE, header=FALSE)
##unlink(temp)

##Goal of analysis:  GDP rankings, by country, income levels, education levels
##o	#For educationraw2:  
##1)	#$V1 (countrycode), $V3 (income group) - just pull out these two columns from ##educationraw2

##create edufinal extracting only rows for $V1-$V3
edufinal <- subset(educationraw2, select = V1:V3)

##o	#For gdpraw2: 
##1)	#$V1 (countrycode), $V2([gdp]ranking) â?? line 6 is where data begins and line 236 ##[6:236] #where it ends; 
##create gdpfinal from gdpraw without headers and pull in rows 6 to 236
gdpfinal <- gdpraw2[6:236,]

##column $V2 just counts the rows â?? not needed
##column $V3 contains all NAs, remove it
##cols $V7 through $V10 contain all NAs, remove them

##count how many NAs are in dataset
sum(is.na(gdpfinal))

##extract columns containing data - $V1, $V4, $V5
gdpfinal2  <- gdpfinal[c(1,4:5)]

##confirm scaled down dataset
str(gdpfinal2)

##o	#For edufinal and gdpfinal2:  
##1)	#rename columns to something meaningful
##now create column names in edufinal and gdpfinal2
names(edufinal) <-c("CountryShortName", "CountryLongName", "IncomeGroup")
names(gdpfinal2) <-c("CountryShortName", "CountryLongName", "GDP")

##confirm the var name changes:
str(edufinal)
str(gdpfinal2)

##2)	#Merge the datasets on CountryShortName
clean01 <- merge(gdpfinal2, edufinal, by="CountryShortName", all=TRUE)

##confirm merge
str(clean01)


##o	#For merged dataset clean01:  
##1)	#In GDP column â?? set NAs to 0.001 and convert it to numeric

##check data in GDP to ensure no NAs
##some values are NA â?? need to set to  0.001
clean01$GDP[is.na(clean01$GDP)] <- 0.001

##now remove commas to convert from char to num
clean01$GDP <- as.numeric(gsub('[,]', '', clean01$GDP))

##confirm commas have been removed and var type is numeric
head(clean01)
tail(clean01)

##2)	#Count NAs in dataset before rows with NAs

##count how many IDs match
sum(!is.na(unique(clean01$GDP)))
##there are 202 IDs that match

##count how many NAs are in dataset
sum(is.na(clean01))
##there are 34 rows that contain NAs

##any NA values are not relevant to analysis, so
##remove those rows from dataset
clean02 <- na.omit(clean01)

##look at data to confirm tidy
str(clean02)
head(clean02, 20)
tail(clean02, 10)

##*> Data Analysis â?? Part 3
##o	#Presentation and Interpretation
##sort data on country short name
clean02[order(clean02$CountryShortName),]
##set IncomeGroup as factor type
##then declare the levels
clean02$IncomeGroup <- as.factor(clean02$IncomeGroup)
levels(clean02$IncomeGroup)

##average GDP rankings for "High income: OECD" 
##and "High income: nonOECD" groups
ddply(clean02, ~IncomeGroup, summarize, avgGDP = mean(GDP))
##Plot by Income Group
qplot(IncomeGroup, data=clean02, geom="density", color=factor(IncomeGroup), xlab="IncomeGroup", ylab="GDP-Ranking")

##and "High income: nonOECD" groups
aggregate(x = clean02$GDP, by = list(clean02$IncomeGroup), FUN = "quantile")

##A two-way contingency table Ranking vs. Income Group
with(clean02, table(cut(GDP, quantile(GDP)), IncomeGroup))	

```

## R Markdown

